web/admin/grails-app/controllers/no/ndla/topics/admin/KeywordController.groovy
package no.ndla.topics.admin

import grails.plugins.springsecurity.Secured
import no.ndla.topics.service.model.NdlaWord
import org.codehaus.jettison.json.JSONArray
import org.codehaus.jettison.json.JSONObject

import groovyx.net.http.HTTPBuilder
import groovyx.net.http.ContentType
import groovyx.net.http.Method
import groovyx.net.http.RESTClient

import javax.annotation.PostConstruct

import static groovyx.net.http.Method.GET
import static groovyx.net.http.ContentType.JSON

import groovy.json.*

import net.ontopia.topicmaps.core.*

import no.ndla.topics.service.NdlaServiceException
import no.ndla.topics.service.NdlaSite
import no.ndla.topics.service.model.NdlaTopic


@Secured(['ROLE_ADMIN','ROLE_KEYWORD_USER'])
class KeywordController{


    def adminTopicService // Dependency Injection (DI) by the Spring container.

    @PostConstruct
    void init() {
        if(null == adminTopicService.getTopicService()){
            adminTopicService.setTopicService();
        }
    }

    def index() {

    }

    def removeKeyword() {
        def langMap = [:]
        def shortMap = [:]
        def Language lang;

        ArrayList<NdlaTopic> languageArray = adminTopicService.getLanguages();
        languageArray.each{ languageItem ->
            langMap.put(languageItem.getIdentifier(),languageItem.names.get("http://psi.oasis-open.org/iso/639/#eng"))
        }

        [languages: langMap, shortMap: shortMap, searchDomain: grailsApplication.config.INDEX_SERVICE_URL, pathPrefix: grailsApplication.config.ndla.topicservice.pathPrefix]
    }

    def lookupKeyword() {

        def langMap = [:]

        ArrayList<NdlaTopic> languageArray = adminTopicService.getLanguages();
        languageArray.each{ languageItem ->
                langMap.put(languageItem.getIdentifier(),languageItem.names.get("http://psi.oasis-open.org/iso/639/#eng"))
        }

        [languages: langMap, searchDomain: grailsApplication.config.INDEX_SERVICE_URL, pathPrefix: grailsApplication.config.ndla.topicservice.pathPrefix, resourceHost: grailsApplication.config.RESOURCE_URI_HOST]
    }

    // Form processing.
    def doRemoveKeyword(RemoveKeywordCommand command) {
        withForm {
            def keywordIdentifier = params.keywordIdentifier

            // Validate form.
            if (command.hasErrors()) {
                flash.warning = "The keyword field cannot be empty."
                redirect(controller: 'keyword', action: 'removeKeyword')
                return
            }
            try {
                def keywordIdentifiers = [keywordIdentifier] // Instance of java.util.List.
                def result = adminTopicService.deleteKeywordsByKeywordId(keywordIdentifiers)
                flash.success = "The keyword was successfully removed."

                [keywordIdentifier: keywordIdentifier] // Hash map is made available to the view for rendering purposes.
            } catch (NdlaServiceException error) {
                flash.error = "An error occurred while trying to remove the keyword."
            }
            redirect(controller: 'keyword', action: 'removeKeyword')
        }.invalidToken {
           // Bad request.
        }
    }

    def updateKeyword() {
        //def http = new HTTPBuilder('http://api.topic.test.ndla.no/')
        def http = new HTTPBuilder('http://localhost:8080/no.ndla.topics/')
        def wordClasses = []

        ArrayList<NdlaTopic> wordClassArray = adminTopicService.getWordClasses()
        wordClassArray.each{ wc ->
            wordClasses.add(capitalize(wc.getIdentifier()))
        }

        def langMap = [:]
        def shortMap = [:]

        ArrayList<NdlaTopic> languageArray = adminTopicService.getLanguages();
        languageArray.each{ languageItem ->
            HashMap<String,String> names = new HashMap<>();
            if(languageItem.psi != "http://psi.topic.ndla.no/#language-neutral" && languageItem.psi != "http://psi.mycurriculum.no/#universal-type"){
                langMap.put(languageItem.psi,languageItem.names.get("http://psi.oasis-open.org/iso/639/#eng"))
                shortMap.put(languageItem.psi,languageItem.psi.substring(languageItem.psi.lastIndexOf("#")+1));
            }

        }

        [wordClasses: wordClasses, langMap: langMap, shortMap: shortMap, searchDomain: grailsApplication.config.INDEX_SERVICE_URL]
    }

    // Form processing.

    def doUpdateKeyword(UpdateKeywordCommand command) {
        withForm {
            def keywordIdentifier = params.keywordIdentifier
            def wordClass = params.wordClass.toLowerCase()
            def visibility = params.visibilityRadios == "visibilityOption1" ? "1" : "0"
            def approvedStatus = params.approvedRadios;
            def processStatus = params.processStateRadios;
            def processMap = [:]
            processMap["0"] = "Not processed"
            processMap["1"] = "Pending"
            processMap["2"] = "Processed"
            if(null == processStatus || "null" == processStatus){
                processStatus = "2";
            }

            def initialProcessState = params.initialProcessState
            def initialApprovalState = params.initialApprovalState;
            def languageSelect = []
            def types = params.typeSelect;

            languageSelect = params.languageSelect;
            //System.out.println("PARAMS: "+params)
            // Validate form.
            if (command.hasErrors()) {
                flash.warning = "The keyword, word class, visibility and approvedStatus fields cannot be empty: "+command.errors.toString()
                redirect(controller: 'keyword', action: 'updateKeyword')
                return
            }

            JSONObject payload = new JSONObject()
            JSONArray outerKeywords = new JSONArray()
            JSONObject keyword = new JSONObject()
            JSONArray innerKeywords = new JSONArray()
            JSONObject keywordStructure = new JSONObject()
            keywordStructure.put('visibility', visibility)
            keywordStructure.put('wordclass', wordClass)

            JSONArray names = new JSONArray()

            params.each { key, val ->
                if(key.contains("#")){
                    JSONObject nametmp = new JSONObject();

                    key = key.substring(key.lastIndexOf("#")+1)
                    if(key != "neutral"){
                        nametmp.put("language","http://psi.oasis-open.org/iso/639/#"+key)
                    }


                    nametmp.put("keyword",val)
                    names.put(nametmp)
                }
            }

            keywordStructure.put('names', names)
            JSONArray jsonTypes = new JSONArray()



            if(types instanceof java.lang.String){
                JSONObject jsonType = new JSONObject()
                jsonType.put("typeId",types)
                jsonTypes.put(jsonType)
            }
            else{
                types.each{ type ->
                    JSONObject jsonType = new JSONObject()
                    jsonType.put("typeId",type)
                    jsonTypes.put(jsonType)
                }
            }


            keywordStructure.put('types', jsonTypes)

            innerKeywords.put(keywordStructure)
            keyword.put("${keywordIdentifier}", innerKeywords)
            outerKeywords.put(keyword)
            payload.put("keywords", outerKeywords)
            //System.out.println("PAYLOAD: "+payload);
            //System.out.println("APPROVED: "+approvedStatus)
            //System.out.println("processStatus: "+processStatus)

            boolean updateSuccess = false;

            try {
                def result = adminTopicService.updateKeywordsByKeywordId(payload.toString())
                updateSuccess = true;
                flash.success = "The keyword was successfully updated."
            } catch (NdlaServiceException error) {
                flash.error = "An error occurred while trying to update the keyword."
            }

            String successMessage = ""
            if (updateSuccess) {
                successMessage += "<li>The keyword was successfully updated</li>"
            }


            boolean wasApproved = false;

            if(!initialApprovalState.equals(approvedStatus)) {
                successMessage += "<ul>"
                try{
                    boolean success = false;
                    if(approvedStatus.equals("true")){
                        success = adminTopicService.approveKeyword(keywordIdentifier)
                        if(success) {
                            successMessage  += "<li>The keyword was successfully approved</li>";
                            flash.success = successMessage
                        }
                        else{
                            flash.error = "An error occurred while trying to approve the keyword."
                        }
                        wasApproved = true;
                    }
                    else{
                        success = adminTopicService.disapproveKeyword(keywordIdentifier);
                        if(success) {
                            successMessage  += "<li>The keyword was successfully disapproved</li>";
                            flash.success = successMessage
                        }
                        else{
                            flash.error = "An error occurred while trying to disapprove the keyword."
                        }
                    }
                }
                catch (NdlaServiceException approveError) {
                    flash.error = "An error occurred while trying to set approval state for the keyword."
                }
            }

            if(!wasApproved){
                if(!initialProcessState.equals(processStatus) && processStatus != "2") {
                    try {
                        boolean success = false;
                        success = adminTopicService.setProcessState(keywordIdentifier, processStatus,"keywords")

web/admin/grails-app/controllers/no/ndla/topics/admin/MetadatasetController.groovy
package no.ndla.topics.admin

import grails.plugins.springsecurity.Secured

@Secured(['ROLE_ADMIN'])
class MetadatasetController {

    def index() {
    	flash.warning = "The metadata sets-related functionality has not been implemented, yet."
        redirect(controller: 'keyword', action: 'lookupKeyword')
    }
}

web/admin/grails-app/views/keyword/addHierarchicalRelation.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
				</ul>
			</div>
		</div>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Keyword</g:link></li>
				<li><g:link controller="keyword" action="removeKeywordNodes" params="['data-toggle': 'tab']">Remove Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addNodeKeywords" params="['data-toggle': 'tab']">Add Content Relation</g:link></li>
				<li class="active"><a href="#tab1" data-toggle="tab">Hierarchical Relation</a></li>
				<li><g:link controller="keyword" action="addHorizontalRelation" params="['data-toggle': 'tab']">Horizontal Relation</g:link></li>
				<li><g:link controller="keyword" action="merge" params="['data-toggle': 'tab']">Merge</g:link></li>
			</ul>
			<p>Add Hierarchical Relation</p>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/addHorizontalRelation.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
				</ul>
			</div>
		</div>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Keyword</g:link></li>
				<li><g:link controller="keyword" action="removeKeywordNodes" params="['data-toggle': 'tab']">Remove Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addNodeKeywords" params="['data-toggle': 'tab']">Add Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addHierarchicalRelation" params="['data-toggle': 'tab']">Hierarchical Relation</g:link></li>
				<li class="active"><a href="#tab1" data-toggle="tab">Horizontal Relation</a></li>
				<li><g:link controller="keyword" action="merge" params="['data-toggle': 'tab']">Merge</g:link></li>
			</ul>
			<p>Add Horizontal Relation</p>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/addKeyword.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
        <r:script>
            $(document).ready(function () {
                searchDomain = $("#searchDomain").val()
                $('#addLanguageButton').click(function () {
                    var selectedLanguageId = $("#languages option:selected").val()
                    var selectedLanguageText = $("#languages option:selected").text()
                    $("#keywordNames").append('<label>' + selectedLanguageText + ' title</label><input type="text" name="name_' + selectedLanguageId + '" id="name_' + selectedLanguageId + '" placeholder="type a ' + selectedLanguageText + ' title" autocomplete="off" value="">');
                    $("#languages option:selected").remove();

                });

                $('body').on('click', "input[name=typeSelect]" ,function(){
                    if(!$(this).is(':checked')) {
                        $(this).parent().remove();
                    }
                });

                $('#keywordByIdTypeTitle').typeahead ({
                    source: function (query, process) {
                    keywords = [];
                    map = {};
                    langMap = [];
                    //var serviceUrl = "http://search.test.ndla.no/ndla_search/keywords/" + query;
                    var serviceUrl = searchDomain+"/sites/all/modules/ndla_search/plugins/ndla_search_ord.ac.php/" + query;
                    var searchLanguage = ""
                    var searchType = $('#typeSelect').val();
                    $( "input[name=languageSelect]" ).each(function(){
                        if($(this).is(':checked') && $(this).val() != ""){
                            var langId = $(this).val().substr($(this).val().indexOf("#")+1)
                            searchLanguage += "language[]="+langId+"&";
                            langMap.push($(this).val())
                        }
                    });
                    searchLanguage = searchLanguage.substr(0,searchLanguage.length -1)
                    serviceUrl += "?" + searchLanguage + "&type=" + searchType;

                    $.ajax({
                        url: serviceUrl,
                        type: 'GET',
                        dataType: 'json',
                        success: function (response) {
                            var data = processJson(response, langMap);
                            $.each(data, function (i, keyword) {
                                var key = keyword.title;

                                if (!(key in map)) {
                                    map[key] = keyword;
                                    keywords.push(key);
                                }
                            });
                            process(keywords);
                        }

                    }, 300);
                    },
                     matcher: function (item) {
                            return true;
                    },
                    updater: function (item) {
                        var typeCheckBoxes = ""
                        for(mkey in map[item]){
                        var stringVal = map[item][mkey];
                        if(typeof(stringVal) != "undefinded"){
                        console.log(mkey)
                            if(mkey.contains('title_eng')) {
                                var langKey = mkey.substr(mkey.lastIndexOf("_")+1);
                                 var checkBox = '<label>'+stringVal+' <g:checkBox name="typeSelect"
                                                                                  value="'+map[item].identifier+'"
                                                                                  checked="true"/></label>';
                                 typeCheckBoxes += checkBox;
                            }
                        }
                      }
                      $("#keyword_types").append(typeCheckBoxes);
                    }
                });

            });

            function processJson(json,langMap) {
                var result = new Array();
                for(var i = 0; i < json.length; ++i) {
                    dataObject = {}

                    var neutral_title = json[i].title_language_neutral
                    jQuery.each(json[i], function(key, val) {
                        if(key.indexOf("title_") > -1 && key.indexOf('_title_') == -1) {
                            var split_arr = key.split("_");
                            if(langMap.indexOf(split_arr[1]) > -1){
                                dataObject[key] = val;
                            }
                        }
                    });

                    neutral_title = typeof (neutral_title) ==  'undefined' ? json[i].title_nob : json[i].title_language_neutral;

                    dataObject['identifier'] = json[i].id
                    dataObject['title'] = neutral_title
                    dataObject['wordclass'] = json[i].wordclass;
                    dataObject['visibility'] = json[i].visibility;
                    dataObject['types'] = json[i].type_id;
                    dataObject['approved'] = json[i].approved;

                    result.push(dataObject);
                }
                return result;
            }
        </r:script>
	</head>
	<body>
    <div class="navbar">
        <g:render template="/actionmenu"model="[param:1]" />
    </div>
		<div class="tabbable">
            <g:render template="submenu" model="[param:2]" />
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<div class="tabbable tabs-right">
						<ul class="nav nav-tabs">
							<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Remove</g:link></li>
							<li><g:link controller="keyword" action="updateKeyword" params="['data-toggle': 'tab']">Update</g:link></li>
							<li class="active"><a href="#tab1-3" data-toggle="tab">Add</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="tab1-3">
								<g:form name="addKeywordForm" useToken="true" action="doAddKeyword">
                                    <g:hiddenField name="searchDomain" value="${searchDomain}" />
                                    <g:each in="${langMap}" var="lang">
                                        <g:checkBox name="languageSelect" class="hiddenLanguageSelect" value="${lang.key}" /></label>
                                    </g:each>
									<fieldset>
										<legend>Add Keyword</legend>
                                        <div id="keywordNames">
                                            <label>English Title</label>
                                            <input type="text" name="name_eng" placeholder="Type an English title...">

                                            <label>Bokmål Title</label>
                                            <input type="text" name="name_nob" placeholder="Type a Bokmål title...">
                                        </div>
                                        <g:select id="languages" from="${nameLangs.entrySet()}" name="languages" optionKey="key" optionValue="value" noSelection="['':'Add a language']"/> <button class="btn" id="addLanguageButton" type="button">Go!</button>
                                        <label>Word Class</label>
                                        <g:select name="wordClass" from="${wordClasses}" noSelection="['':'-Choose word class-']" />
                                        <label>Visible?</label>
                                        <label class="radio">
                                            <g:radio name="visibilityRadios" id="visibilityRadios1" value="visibilityOption1" checked="true" />Yes
                                        </label>
                                        <label class="radio">
                                            <g:radio name="visibilityRadios" id="visibilityRadios2" value="visibilityOption2" />No
                                        </label>


                                        <div id="keywordTypesWrapper">
                                            <div id="keyword_types">
                                                <p id="keyword_type_label">Keyword types</p>
                                            </div>
                                            <label>Add a new type <input type="text" name="keywordByIdTypeTitle" id="keywordByIdTypeTitle" placeholder="Type a type identifier..." autocomplete="off"> </label>
                                        </div>

										<br />
										<br />
										<g:submitButton name="submit" class="btn btn-success" value="Add" />
									</fieldset>
								</g:form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/addNodeKeywords.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
				</ul>
			</div>
		</div>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Keyword</g:link></li>
				<li><g:link controller="keyword" action="removeKeywordNodes" params="['data-toggle': 'tab']">Remove Content Relation</g:link></li>
				<li class="active"><a href="#tab1" data-toggle="tab">Add Content Relation</a></li>
				<li><g:link controller="keyword" action="addHierarchicalRelation" params="['data-toggle': 'tab']">Hierarchical Relation</g:link></li>
				<li><g:link controller="keyword" action="addHorizontalRelation" params="['data-toggle': 'tab']">Horizontal Relation</g:link></li>
				<li><g:link controller="keyword" action="merge" params="['data-toggle': 'tab']">Merge</g:link></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<div class="tabbable tabs-right">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#tab3-1" data-toggle="tab">Node-Keywords</a></li>
							<li><g:link controller="keyword" action="addSubjectKeywords" params="['data-toggle': 'tab']">Subject-Keywords</g:link></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="tab3-1">
								<p>Node-Keywords</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/index.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
                    <li><g:link controller="indexSOLR" action="updateIndexAll">SOLR index</g:link></li>
                    <li><g:link controller="ontology" action="getSubjects">Ontology</g:link></li>
				</ul>
			</div>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/merge.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
				</ul>
			</div>
		</div>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Keyword</g:link></li>
				<li><g:link controller="keyword" action="removeKeywordNodes" params="['data-toggle': 'tab']">Remove Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addNodeKeywords" params="['data-toggle': 'tab']">Add Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addHierarchicalRelation" params="['data-toggle': 'tab']">Hierarchical Relation</g:link></li>
				<li><g:link controller="keyword" action="addHorizontalRelation" params="['data-toggle': 'tab']">Horizontal Relation</g:link></li>
				<li class="active"><a href="#tab1" data-toggle="tab">Merge</a></li>
			</ul>
			<p>Merge</p>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/removeKeywordSubjects.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
				</ul>
			</div>
		</div>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Keywords</g:link></li>
				<li class="active"><a href="#tab2" data-toggle="tab">Remove Content Relation</a></li>
				<li><g:link controller="keyword" action="addNodeKeywords" params="['data-toggle': 'tab']">Add Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addHierarchicalRelation" params="['data-toggle': 'tab']">Hierarchical Relation</g:link></li>
				<li><g:link controller="keyword" action="addHorizontalRelation" params="['data-toggle': 'tab']">Horizontal Relation</g:link></li>
				<li><g:link controller="keyword" action="merge" params="['data-toggle': 'tab']">Merge</g:link></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<div class="tabbable tabs-right">
						<ul class="nav nav-tabs">
							<li><g:link controller="keyword" action="removeKeywordNodes" params="['data-toggle': 'tab']">Keyword-Nodes</g:link></li>
							<li><g:link controller="keyword" action="removeNodeKeywords" params="['data-toggle': 'tab']">Node-Keywords</g:link></li>
							<li class="active"><a href="#tab2-3" data-toggle="tab">Keyword-Subjects</a></li>
							<li><g:link controller="keyword" action="removeSubjectKeywords" params="['data-toggle': 'tab']">Subject-Keywords</g:link></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="tab2-3">
								<p>Keyword-Subjects</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

web/admin/grails-app/views/keyword/removeNodeKeywords.gsp
<!doctype html>
<html>
	<head>
	    <meta name="layout" content="main"/>
	    <title>NDLA Topics Admin Application - Keywords</title>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">Actions</a>
				<ul class="nav">
					<li class="active"><g:link controller="keyword" action="removeKeyword">Keywords</g:link></li>
					<li><g:link controller="topic" action="index">Topics</g:link></li>
					<li><g:link controller="curriculum" action="index">Curricula</g:link></li>
					<li><g:link controller="metadataset" action="index">Metadata Sets</g:link></li>
				</ul>
			</div>
		</div>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li><g:link controller="keyword" action="removeKeyword" params="['data-toggle': 'tab']">Keywords</g:link></li>
				<li class="active"><a href="#tab2" data-toggle="tab">Remove Content Relation</a></li>
				<li><g:link controller="keyword" action="addNodeKeywords" params="['data-toggle': 'tab']">Add Content Relation</g:link></li>
				<li><g:link controller="keyword" action="addHierarchicalRelation" params="['data-toggle': 'tab']">Hierarchical Relation</g:link></li>
				<li><g:link controller="keyword" action="addHorizontalRelation" params="['data-toggle': 'tab']">Horizontal Relation</g:link></li>
				<li><g:link controller="keyword" action="merge" params="['data-toggle': 'tab']">Merge</g:link></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<div class="tabbable tabs-right">
						<ul class="nav nav-tabs">
							<li><g:link controller="keyword" action="removeKeywordNodes" params="['data-toggle': 'tab']">Keyword-Nodes</g:link></li>
							<li class="active"><a href="#tab2-2" data-toggle="tab">Node-Keywords</a></li>
							<li><g:link controller="keyword" action="removeKeywordSubjects" params="['data-toggle': 'tab']">Keyword-Subjects</g:link></li>
							<li><g:link controller="keyword" action="removeSubjectKeywords" params="['data-toggle': 'tab']">Subject-Keywords</g:link></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="tab2-2">
								<p>Node-Keywords</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>